name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "json, dom, mbstring"

      - name: "Cache dependencies"
        uses: "actions/cache@v1.1.2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php }}-composer-cache-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-cache"

      - name: "Install dependencies"
        run: "composer update --no-suggest --no-interaction --prefer-dist --no-progress"

      - name: "Run tests"
        run: "composer phpunit"

  static-analysis:
    name: "PHPStan"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "json, dom, mbstring"

      - name: "Cache dependencies"
        uses: "actions/cache@v1.1.2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php }}-composer-cache-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-cache"

      - name: "Install dependencies"
        run: "composer update --no-suggest --no-interaction --prefer-dist --no-progress"

      - name: "PHPStan"
        run: "composer phpstan"

  coding-standards:
    name: "Coding Standard"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "json, dom, mbstring"

      - name: "Validate Composer"
        run: "composer validate"

      - name: "Cache dependencies"
        uses: "actions/cache@v1.1.2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php }}-composer-cache-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-cache"

      - name: "Install dependencies"
        run: "composer update --no-suggest --no-interaction --prefer-dist --no-progress"

      - name: "Normalize composer"
        run: "composer normalize"

      - name: "Check code styles"
        run: "composer phpcs"
